---
language: python
services: docker

env:
  global:
    - ROLE_NAME: vsftpd
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  - pip install molecule yamllint ansible-lint ansible molecule[docker] docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME hemanth22.$ROLE_NAME
  - cd hemanth22.$ROLE_NAME

script:
  - molecule test

after_failure:
  - wget -O createIssue.sh https://git.io/CreateIssue
  - chmod 777 createIssue.sh
  - ./createIssue.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos